#! /usr/bin/python3
import signal
import rospy
import os

from src.robot_generator import *
# keyboard interrupt function
def keyBoardINT(signum, frame):  
    print('You pressed Ctrl+C!')
    os.kill(os.getpid(), signal.SIGKILL)

if __name__ == '__main__': 

    signal.signal(signal.SIGINT, keyBoardINT)  
    signal.signal(signal.SIGTERM, keyBoardINT) 

    rospy.init_node('py_strategy', anonymous=True)
    robot_generator = RobotGenerator()
    robot_list = robot_generator.selectRobot()
    rate = rospy.Rate(5)

    while not rospy.is_shutdown():        

        for update_role in enumerate(robot_generator.update_role):
            if update_role[1] == True:
                robot_generator.selectRobot(robot_list=robot_list, number=update_role[0])
                robot_generator.update_role[update_role[0]] = False
       
        for robot in robot_list:
            if robot is not None:
                robot.run()
        
        rate.sleep()